- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Find out playbook's path
      shell: pwd
      register: playbook_path_output

    - name: Show path
      debug:
        msg: "{{ playbook_path_output.stdout }}/../"

    - name: remove symlinks
      file: path="{{ playbook_path_output.stdout }}/../{{ item }}"
        state=absent
        force=yes
      with_items:
        - cluster.yml
        - cluster.rkestate
        - id_rsa
        - id_rsa.pub
        - kube_config_cluster.yml

    - name: remove stale files
      file: path="{{ playbook_path_output.stdout }}/../terraform/{{ item }}"
        state=absent
        force=yes
      with_items:
        - cluster.yml
        - cluster.rkestate
        - id_rsa
        - id_rsa.pub
        - kube_config_cluster.yml
