---
# Prepare for correct python setup
- hosts: tag_engine_docker
  become: yes
  gather_facts: true
  vars_files:
    - ../secret

  vars:
    ansible_user: ubuntu
    ansible_ssh_user: ubuntu
    ansible_python_interpreter: /usr/bin/python3

    # pip_install_packages:
    #   - name: setuptools
    #   - name: docker
    docker_users:
      - ubuntu
      - rke

  roles:
    - docker
    - update
    - rke

# Prepare storage
- hosts: tag_role_longhorn
  become: yes

  vars:
    ansible_user: ubuntu
    ansible_ssh_user: ubuntu
    ansible_python_interpreter: /usr/bin/python3

  roles:
    - longhorn
